- terminal-demo-app/src/APIKeyForm/APIKeyForm.jsx
- terminal-demo-app/src/Logs/Logs.jsx
- terminal-demo-app/src/MainPage.jsx
- terminal-demo-app/src/lib/Group/Group.jsx
- terminal-demo-app/src/lib/TextInput/TextInput.jsx
I moved the 'general' components to src/lib and forgot to update the import paths.
> Fix broken paths

- terminal-demo-app/package-lock.json
- terminal-demo-app/package.json
- terminal-demo-app/src/ConnectionInfo/ConnectionInfo.jsx
- terminal-demo-app/src/MainPage.jsx
- terminal-demo-app/src/lib/OverflowMenu/OverflowMenu.jsx
- terminal-demo-app/src/lib/OverflowMenu/OverflowMenuItem.jsx
> Add Connection Info component plus OverflowMenu

- .gitignore
- terminal-demo-app/src/APIKeyForm/APIKeyForm.jsx
- terminal-demo-app/src/ConnectionInfo/ConnectionInfo.jsx
- terminal-demo-app/src/Forms/BackendURLForm.jsx
- terminal-demo-app/src/Forms/CommonWorkflows.jsx
- terminal-demo-app/src/Forms/DiscoverReaders.jsx
- terminal-demo-app/src/Forms/RegisterNewReader.jsx
- terminal-demo-app/src/Logs/Logs.jsx
- terminal-demo-app/src/MainPage.jsx
- terminal-demo-app/src/lib/Button/Button.jsx
- terminal-demo-app/src/lib/Link/Link.jsx
- terminal-demo-app/src/lib/Text/Text.css
- terminal-demo-app/src/lib/Text/Text.jsx
- terminal-demo-app/src/lib/TextInput/TextInput.jsx
- terminal-demo-app/yarn.lock
Screen 1 of: https://github.com/stripe/stripe-terminal-js/issues/11
> More frontend work

- terminal-demo-app/src/MainPage.jsx
- terminal-demo-app/src/backend.js
r? @esandler-stripe 
cc @fay-stripe 
just some minor copy edits, this looks great overall though! ✨
> tweak comments in example

- terminal-demo-app/src/ConnectionInfo/ConnectionInfo.jsx
- terminal-demo-app/src/Forms/BackendURLForm.jsx
- terminal-demo-app/src/Forms/DiscoverReaders.jsx
- terminal-demo-app/src/Forms/RegisterNewReader.jsx
- terminal-demo-app/src/Logs/Logs.css
- terminal-demo-app/src/Logs/Logs.jsx
- terminal-demo-app/src/components/Button/Button.jsx
- terminal-demo-app/src/components/InfoTooltip/InfoTooltip.css
- terminal-demo-app/src/components/InfoTooltip/InfoTooltip.jsx
- terminal-demo-app/src/components/Text/Text.jsx
> Rename API key to Backend URL and add simulator copy

- README.md
> Add line about reader simulator to README

- package-lock.json
- src/Forms/RegisterNewReader.jsx
> Add labels and examples for reader registration form

- README.md
- src/Logs/Logs.jsx
- src/MainPage.jsx
- src/logger.js
> add docs to logger and fix connecting to simulator

- package-lock.json
- package.json
- src/Logs/Logs.css
- src/Logs/Logs.jsx
- src/MainPage.jsx
- src/logger.js
Add animations to logs appearing and prevent them from coming in out of order
> Logs fix with animations

- package-lock.json
Manually updated the package-lock.json file to ensure dependencies are pulled over TLS.
> Update package-lock.json to pull dependencies over TLS

- src/MainPage.jsx
This uses a local JS SDK build from @esandler-stripe, with some of the API changes:
* discovery method `registered` -> `internet`
* `connectResult.connection` was removed, using `connectResult` and `connectResult.reader`
* Remove `tip_presentations`
* `processPayment` instead of `confirmPaymentIntent`
Builds on #51
> Update WIP tipping branch with latest SDK changes.

- public/index.html
- src/MainPage.jsx
- src/client.js
> Update to use rc1 release

- src/Forms/CartForm.jsx
- src/Forms/CommonWorkflows.jsx
- src/components/Button/Button.jsx
Fixes alignment issue of text on buttons in js example app.
Testing:
> Fix alignment on buttons.

- package-lock.json
👋 hej
+ Does what it says on the tin - just updating vulnerable dependencies. 
+ The npm audit now runs clean ⛑
> run npm audit and fix vulnerabilities

- public/index.html
- src/Forms/CartForm.jsx
- src/Forms/RefundForm.jsx
- src/MainPage.jsx
- src/client.js
- Interact refund support in frontend
- CAD currency support in frontend
- CA docs
> Add support for Canada features

- src/Forms/CommonWorkflows.jsx
- src/Forms/TestPaymentMethods.jsx
- src/MainPage.jsx
- src/components/TextInput/TextInput.jsx
Merge after https://git.corp.stripe.com/stripe-internal/pos-js-v1/pull/363 is released
> Add support for simulated test cards and payment methods

- src/ConnectionInfo/ConnectionInfo.jsx
> fixes keypad icon

- src/Forms/Readers.jsx
- src/Forms/RegisterNewReader.jsx
- src/MainPage.jsx
- src/client.js
- src/components/Select/Select.css
- src/components/Select/Select.jsx
Depends on https://github.com/stripe/example-terminal-backend/pull/32
https://user-images.githubusercontent.com/56042317/117860320-0289b980-b245-11eb-9ea0-d25e4f50e64e.mp4
> Add location select to reader registration form

- src/MainPage.jsx
> account for $0 (empty) tax in line item (previously rendered as NaN breaking total amount)

- .npmrc
- package-lock.json
- package.json
- src/components/Link/Link.jsx
This PR updates CRA to the latest version which should resolve a good deal of our dependabot alerts.
Validated by spinning up the app, worked 🎉
> update CRA to latest and greatest

- src/Forms/CartForm.jsx
Add DKK and SEK to supported currencies
> add dkk and sek currencies

- package-lock.json
Minimist <=1.2.5 is vulnerable to Prototype Pollution
> Bump minimist to 1.2.6
